site_name: 大鼻子
copyright: '版权 &copy; 2016 - 2017 wohugb.github.io'
pages:
  - 概述: index.md
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - footnotes
  - meta
  - toc:
      permalink: true